//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetLocations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetLocations()
        {
            this.AssetLocations1 = new HashSet<AssetLocations>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
    
        public virtual Asset Asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetLocations> AssetLocations1 { get; set; }
        public virtual AssetLocations AssetLocations2 { get; set; }
        public string Code { get; internal set; }
    }
}
